## MCIT
# storePassword=MCIT@@1400
# keyPassword=MCIT@@1400
# storeFile=../app/mcit-keystore.jks

## GET
 storePassword=getgroup
 keyPassword=getgroup
 storeFile=../app/get-keystore.jks

keyAlias=key
